version: 1.0.{build}
image: Previous Visual Studio 2022
configuration: Release
before_build:
- ps: nuget restore
build:
  verbosity: minimal
before_package:
- pwsh: >-
    $version = (get-item ".\src\Appysights\bin\Release\net6.0-windows\Appysights.exe").VersionInfo | % {("{0}.{1}.{2}" -f $_.ProductMajorPart,$_.ProductMinorPart,$_.ProductBuildPart)};

    Set-Alias Squirrel ($env:USERPROFILE + "\.nuget\packages\clowd.squirrel\2.7.34-pre\tools\Squirrel.exe");
    Squirrel pack --packName "Appysights" --packVersion $version --packAuthors "SYLC" --packDirectory ".\src\Appysights\bin\Release\net6.0-windows";
artifacts:
- path: C:\projects\appysights\Releases\Releases\*.exe
- path: C:\projects\appysights\Releases\Releases\*.nupkg
- path: C:\projects\appysights\Releases\Releases\RELEASES
deploy:
- provider: GitHub
  auth_token:
    secure: kkPYVySvzbfT5BNnZ7x+IObebWn8ZTbiw/6sQtzhI4sS6zIV2cGmSmVVyIlOONAr
  draft: true