version: 1.0.{build}
image: Previous Visual Studio 2022
configuration: Release
before_build:
- ps: nuget restore
build:
  verbosity: minimal
before_package:
- pwsh: >-
    $version = (get-item ".\src\Appysights\bin\Release\net6.0-windows\Appysights.exe").VersionInfo | % {("{0}.{1}.{2}" -f $_.ProductMajorPart,$_.ProductMinorPart,$_.ProductBuildPart)}

    $env:USERPROFILE + "\.nuget\packages\Clowd.Squirrel\2.7.34-pre\tools pack --packName "Appysights" --packVersion $version --packAuthors "SYLC" --packDirectory ".\src\Appysights\bin\Release\net6.0-windows"
after_build:
- pwsh: Rename-Item -Path ".\Releases\Setup.exe" -NewName "AppLurkerSetup.exe"
artifacts:
- path: Releases\*.exe
- path: Releases\*.nupkg
- path: Releases\RELEASES
deploy:
- provider: GitHub
  auth_token:
    secure: kkPYVySvzbfT5BNnZ7x+IObebWn8ZTbiw/6sQtzhI4sS6zIV2cGmSmVVyIlOONAr
  draft: true